### ISSUE TITLE
can i change app_version

### ISSUE THREAD

**Issue by wh0am1Q** [thedemons/opentele#51]
I noticed that the app_version in the library is 8.4.1

is there any way to modify this?

**Comment by thedemons** [comment]
Hi, sorry for the late reply.

Do you mean the API app_version? If so, you can create your own custom API using this:
```python
from opentele.api import APIData

api = APIData(
    api_id=2040,
    api_hash="b18441a1ff607e10a989891a5462e627",
    device_model="Desktop",
    system_version="Windows 10",
    app_version="3.4.3 x64", # change the app_version here
    lang_code="en",
    system_lang_code="en-US",
    lang_pack="tdesktop")
```

You can get the API parameters [here](https://opentele.readthedocs.io/en/latest/documentation/authorization/api/#class-telegramdesktop)

**Comment by wh0am1Q** [comment]
thank you for your reply. I would like to ask 8.4.1 (2522)    what does this (2522)  mean?

If I change the version to 8.5.1 does this (2522) also need to be replaced

**Comment by thedemons** [comment]
\

> thank you for your reply. I would like to ask 8.4.1 (2522) what does this (2522) mean?
> 
> If I change the version to 8.5.1 does this (2522) also need to be replaced

I don't know what is that number either, but you can find it in the releases of [Telegram Android](https://github.com/DrKLO/Telegram/releases), the latest version is `8.6.1 (2594)`

**Comment by wh0am1Q** [comment]
OK。 thank for your help

**Comment by thedemons** [comment]
> OK。 thank for your help

No problem, I'll close the issue then
