### ISSUE TITLE
Strange device name

### ISSUE THREAD

**Issue by dommeo228** [thedemons/opentele#67]
Is it ok?)
device "HTC HTC M8Ss"
SDK 25
8.4.1 (2522)

![image](https://user-images.githubusercontent.com/56001303/179872877-d4e30483-0091-4736-823e-fdafa8379e42.png)

**Comment by thedemons** [comment]
Yes, this is totally fine, i guess it's some china phone

**Comment by dommeo228** [comment]
ok, thank u for ur project)
