### ISSUE TITLE
tdesk.isLoaded() failed assertion with new tdatas

### ISSUE THREAD

**Issue by Chronosms** [thedemons/opentele#69]
**Describe the bug**
You can capture the problem if you'll try to import fresh new tdatas, I think tdata folder structure was changed by Telegram

**To Reproduce**
1. Get fresh new tdata
2. Try to load it with TDesktop

**Expected behavior**
Loaded tdesk object with account(s) loaded

**Snippet**
```python
    try:
        tdesk = TDesktop(f"{tdata}")
        assert tdesk.isLoaded()
    except:
        print('No accounts loaded, skipping')
        accounts_not_loaded += 1
        continue
```

**Comment by Ch4ttY** [comment]
opentele.exception.OpenTeleException: Unexpected Exception: No account has been loaded

On 4.2 version

**Comment by Chronosms** [comment]
Any updates here?

**Comment by staseek** [comment]
https://github.com/thedemons/opentele/pull/74/files - simple fix for this situation.

**Comment by Chronosms** [comment]
> https://github.com/thedemons/opentele/pull/74/files - simple fix for this situation. 

I'll try this hotfix ASAP, thanks

**Comment by Chronosms** [comment]
It works, thank you!
